$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root
Write-Host '=== Auto Director PC Worker - HTTPS sécurisé ===' -ForegroundColor Cyan

function Test-RealPython([string]$Path){if(-not $Path -or -not(Test-Path $Path)){return $false};$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{& $Path -c "import sys; raise SystemExit(0 if sys.version_info >= (3,10) else 2)" 2>$null|Out-Null;return($LASTEXITCODE -eq 0)}catch{return $false}finally{$ErrorActionPreference=$old}}
function Resolve-RealPython{$candidates=New-Object System.Collections.Generic.List[string];if($env:AUTO_DIRECTOR_PYTHON){$candidates.Add($env:AUTO_DIRECTOR_PYTHON)};foreach($p in @((Join-Path $env:LOCALAPPDATA 'Programs\Python\Python313\python.exe'),(Join-Path $env:LOCALAPPDATA 'Programs\Python\Python312\python.exe'),(Join-Path $env:LOCALAPPDATA 'Programs\Python\Python311\python.exe'),(Join-Path $env:ProgramFiles 'Python313\python.exe'),(Join-Path $env:ProgramFiles 'Python312\python.exe'),(Join-Path $env:ProgramFiles 'Python311\python.exe'))){if($p){$candidates.Add($p)}};try{Get-ChildItem (Join-Path $env:LOCALAPPDATA 'Programs\Python') -Directory -ErrorAction SilentlyContinue|Sort-Object Name -Descending|ForEach-Object{$p=Join-Path $_.FullName 'python.exe';if(Test-Path $p){$candidates.Add($p)}}}catch{};try{$cmd=Get-Command python.exe -ErrorAction SilentlyContinue;if($cmd -and $cmd.Source -and $cmd.Source -notmatch '\\WindowsApps\\'){$candidates.Add($cmd.Source)}}catch{};foreach($p in $candidates){if(Test-RealPython $p){return $p}};$py=Get-Command py.exe -ErrorAction SilentlyContinue;if($py){foreach($selector in @('-3.13','-3.12','-3.11','-3')){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$resolved=& $py.Source $selector -c "import sys; print(sys.executable)" 2>$null;if($LASTEXITCODE -eq 0 -and $resolved){$path=([string]($resolved|Select-Object -Last 1)).Trim();if(Test-RealPython $path){return $path}}}catch{}finally{$ErrorActionPreference=$old}}};return $null}
$PythonExe=Resolve-RealPython;if(-not $PythonExe){throw 'Python réel introuvable. Réinstalle le worker PC : l installateur ajoutera Python 3.12 automatiquement.'};$env:AUTO_DIRECTOR_PYTHON=$PythonExe;Write-Host "Python: $PythonExe" -ForegroundColor DarkGray

$EnvFile=Join-Path $PSScriptRoot '.env';if(-not(Test-Path $EnvFile)){Copy-Item (Join-Path $PSScriptRoot '.env.example') $EnvFile}
function Import-EnvFile([string]$Path,[bool]$Overwrite=$true){if(-not(Test-Path $Path)){return};Get-Content $Path|ForEach-Object{if($_ -match '^\s*#' -or $_ -notmatch '='){return};$parts=$_ -split '=',2;$key=$parts[0].Trim();$value=$parts[1].Trim();if($Overwrite -or -not[Environment]::GetEnvironmentVariable($key,'Process')){[Environment]::SetEnvironmentVariable($key,$value,'Process')}}}
Import-EnvFile $EnvFile $true
$StudioUrl=if($env:STUDIO_URL){$env:STUDIO_URL.TrimEnd('/')}else{'https://auto-director-web.onrender.com'};if($StudioUrl -ne 'https://auto-director-web.onrender.com'){throw 'STUDIO_URL non autorisée.'}
if(-not $env:WORKER_TOKEN){Write-Host "Connexion au Studio: $StudioUrl" -ForegroundColor Cyan;$Secure=Read-Host 'Mot de passe du Studio' -AsSecureString;$Ptr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure);try{$StudioPassword=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($Ptr)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($Ptr)};if(-not $StudioPassword){throw 'Mot de passe du Studio requis.'};try{$LoginBody=@{password=$StudioPassword}|ConvertTo-Json -Compress;$Login=Invoke-RestMethod -Method Post -Uri "$StudioUrl/api/login" -ContentType 'application/json' -Body $LoginBody -TimeoutSec 20;if(-not $Login.token){throw 'Session Studio absente.'};$Headers=@{Authorization="Bearer $($Login.token)"};$Session=Invoke-RestMethod -Method Post -Uri "$StudioUrl/api/local-worker/session" -Headers $Headers -ContentType 'application/json' -Body '{"label":"windows-manual"}' -TimeoutSec 20;if(-not $Session.workerToken){throw 'Jeton worker absent.'};$env:WORKER_TOKEN=[string]$Session.workerToken}finally{$StudioPassword=$null;$LoginBody=$null;$Login=$null}}
$env:STUDIO_URL=$StudioUrl;$env:REMOTE_WORKER_MODE='1';$env:WORKER_KIND='local';$env:PYTHONUNBUFFERED='1'

if($env:AUTO_PROFILE -ne '0'){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{& $PythonExe (Join-Path $PSScriptRoot 'detect_profile.py') 2>&1|Out-Host;$profileCode=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($profileCode -ne 0){Write-Host 'Profil matériel auto indisponible: profil sûr.' -ForegroundColor Yellow};Import-EnvFile (Join-Path $PSScriptRoot '.auto_profile.env') $true}
if(-not $env:PROFILE_NAME){$env:PROFILE_NAME='safe-unknown'};if(-not $env:RENDER_WIDTH){$env:RENDER_WIDTH='720'};if(-not $env:RENDER_HEIGHT){$env:RENDER_HEIGHT='1280'};if(-not $env:RENDER_FPS){$env:RENDER_FPS='24'};if(-not $env:FFMPEG_THREADS){$env:FFMPEG_THREADS='2'};if(-not $env:MOMENT_SAMPLES){$env:MOMENT_SAMPLES='5'};if(-not $env:MAX_REVISIONS){$env:MAX_REVISIONS='0'};if(-not $env:RENDER_CRF){$env:RENDER_CRF='20'};if(-not $env:RENDER_PRESET){$env:RENDER_PRESET='veryfast'};if(-not $env:LOCAL_TRANSCRIBE){$env:LOCAL_TRANSCRIBE='0'};if(-not $env:LOCAL_WHISPER_MODEL){$env:LOCAL_WHISPER_MODEL='tiny'};if(-not $env:LOCAL_WHISPER_THREADS){$env:LOCAL_WHISPER_THREADS='1'};if(-not $env:LOCAL_QUALITY_ENGINE){$env:LOCAL_QUALITY_ENGINE='0'};if(-not $env:ADVANCED_SCENE_DETECT){$env:ADVANCED_SCENE_DETECT='0'};if(-not $env:SMART_CROP){$env:SMART_CROP='0'};if(-not $env:AUDIO_BEAT_ANALYSIS){$env:AUDIO_BEAT_ANALYSIS='0'}
$env:OMP_NUM_THREADS=$env:FFMPEG_THREADS;$env:MKL_NUM_THREADS=$env:FFMPEG_THREADS;$env:OPENBLAS_NUM_THREADS=$env:FFMPEG_THREADS;$env:OLLAMA_NUM_PARALLEL='1';$env:OLLAMA_MAX_LOADED_MODELS='1';$env:OLLAMA_MAX_QUEUE='1';$env:OLLAMA_KEEP_ALIVE='90s';try{[System.Diagnostics.Process]::GetCurrentProcess().PriorityClass='BelowNormal'}catch{}
Write-Host "Profil: $env:PROFILE_NAME" -ForegroundColor Green;Write-Host "Rendu: $env:RENDER_WIDTH x $env:RENDER_HEIGHT @ $env:RENDER_FPS fps · CRF $env:RENDER_CRF · $env:RENDER_PRESET" -ForegroundColor Green;Write-Host "Charge limitée: FFmpeg=$env:FFMPEG_THREADS threads | analyse=$env:MOMENT_SAMPLES | révisions=$env:MAX_REVISIONS" -ForegroundColor Green;Write-Host ("Quality Engine: "+$(if($env:LOCAL_QUALITY_ENGINE -eq '1'){'ON'}else{'fallback core'})) -ForegroundColor Green

$Venv=Join-Path $Root '.venv-local';$VenvPython=Join-Path $Venv 'Scripts\python.exe';if(-not(Test-Path $VenvPython)){Write-Host 'Création de l environnement Python local...' -ForegroundColor Cyan;$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{& $PythonExe -m venv $Venv 2>&1|Out-Host;$venvCode=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($venvCode -ne 0){throw 'Création de l environnement Python impossible.'}}
$ReqPath=Join-Path $Root 'requirements.txt';$ReqMarker=Join-Path $Venv '.requirements.sha256';$ReqHash=(Get-FileHash $ReqPath -Algorithm SHA256).Hash;$InstalledHash=if(Test-Path $ReqMarker){(Get-Content $ReqMarker -Raw).Trim()}else{''}
if($ReqHash -ne $InstalledHash){Write-Host 'Mise à jour des dépendances du worker...' -ForegroundColor Cyan;& $VenvPython -m pip install --disable-pip-version-check -r $ReqPath;if($LASTEXITCODE -ne 0){throw 'Installation Python du worker impossible.'};Set-Content -Path $ReqMarker -Value $ReqHash -Encoding ASCII}else{Write-Host 'Dépendances Python déjà à jour.' -ForegroundColor DarkGray}
if($env:LOCAL_TRANSCRIBE -eq '1'){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{& $VenvPython -c "import faster_whisper" 2>$null|Out-Null;$whisperCode=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($whisperCode -ne 0){Write-Host 'Préparation de la transcription locale légère...' -ForegroundColor Cyan;& $VenvPython -m pip install --disable-pip-version-check 'faster-whisper>=1.1,<2';if($LASTEXITCODE -ne 0){Write-Host 'Transcription indisponible: le montage continuera sans elle.' -ForegroundColor Yellow;$env:LOCAL_TRANSCRIBE='0'}}}
if($env:LOCAL_QUALITY_ENGINE -eq '1'){
  $QualityReq=Join-Path $PSScriptRoot 'requirements-quality.txt';$QualityMarker=Join-Path $Venv '.quality-requirements.sha256'
  if(Test-Path $QualityReq){$QualityHash=(Get-FileHash $QualityReq -Algorithm SHA256).Hash;$QualityInstalled=if(Test-Path $QualityMarker){(Get-Content $QualityMarker -Raw).Trim()}else{''};if($QualityHash -ne $QualityInstalled){Write-Host 'Préparation du Quality Engine open source...' -ForegroundColor Cyan;$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{& $VenvPython -m pip install --disable-pip-version-check -r $QualityReq;$qualityCode=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($qualityCode -eq 0){Set-Content -Path $QualityMarker -Value $QualityHash -Encoding ASCII}else{Write-Host 'Quality Engine lourd indisponible: fallback core sécurisé.' -ForegroundColor Yellow;$env:LOCAL_QUALITY_ENGINE='0';$env:ADVANCED_SCENE_DETECT='0';$env:SMART_CROP='0';$env:AUDIO_BEAT_ANALYSIS='0'}}}
}

$UseLocalAI=($env:LOCAL_AI_AUTO_ENABLED -eq '1' -and $env:LOCAL_VLM_URL);if($UseLocalAI){if(-not(Get-Command ollama -ErrorAction SilentlyContinue)){Write-Host 'Ollama absent: fallback Director V9.1.' -ForegroundColor Yellow;$env:LOCAL_VLM_URL=''}else{$ready=$false;try{Invoke-RestMethod -Uri 'http://127.0.0.1:11434/api/tags' -TimeoutSec 3|Out-Null;$ready=$true}catch{try{Start-Process -FilePath 'ollama' -ArgumentList 'serve' -WindowStyle Hidden;Start-Sleep -Seconds 4;Invoke-RestMethod -Uri 'http://127.0.0.1:11434/api/tags' -TimeoutSec 5|Out-Null;$ready=$true}catch{$ready=$false}};if($ready){$model=if($env:LOCAL_VLM_MODEL){$env:LOCAL_VLM_MODEL}else{'qwen2.5vl:3b'};$installed=$false;try{$list=ollama list|Out-String;if($list -match [regex]::Escape($model)){$installed=$true}}catch{};if(-not $installed){try{ollama pull $model}catch{$env:LOCAL_VLM_URL=''}}}else{$env:LOCAL_VLM_URL=''}}}else{$env:LOCAL_VLM_URL=''}
Write-Host 'Diagnostic sécurisé...' -ForegroundColor Cyan;& $VenvPython (Join-Path $PSScriptRoot 'doctor.py');if($LASTEXITCODE -ne 0){throw 'Le diagnostic a détecté un problème critique.'}
Write-Host '';Write-Host 'Worker PC démarré. Il devient prioritaire sur Render quand son heartbeat HTTPS est reçu.' -ForegroundColor Green;& $VenvPython (Join-Path $PSScriptRoot 'http_worker_v2.py')
